//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WalletTransaction
    {
        public tbl_WalletTransaction()
        {
            this.tbl_fastTransDetails = new HashSet<tbl_fastTransDetails>();
        }
    
        public int transaction_ID { get; set; }
        public int user_id { get; set; }
        public string transaction_Title { get; set; }
        public System.DateTime transaction_datetime { get; set; }
        public string Debit { get; set; }
        public string Credit { get; set; }
        public string Balance { get; set; }
        public string rechargedBy { get; set; }
    
        public virtual ICollection<tbl_fastTransDetails> tbl_fastTransDetails { get; set; }
        public virtual tbl_profile tbl_profile { get; set; }
    }
}
