//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fastRide
    {
        public tbl_fastRide()
        {
            this.tbl_fastRide_canceled = new HashSet<tbl_fastRide_canceled>();
            this.tbl_fastRideDetails = new HashSet<tbl_fastRideDetails>();
            this.tbl_fastUserRating = new HashSet<tbl_fastUserRating>();
        }
    
        public int fastRide_ID { get; set; }
        public int user_id { get; set; }
        public string from_place { get; set; }
        public string to_place { get; set; }
        public string from_place_persian { get; set; }
        public string to_place_persian { get; set; }
        public string statusType { get; set; }
        public string LatLong { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string vehicleType { get; set; }
        public Nullable<bool> VehicleTypeIsNormal { get; set; }
        public string from_LatLong { get; set; }
        public string to_LatLong { get; set; }
    
        public virtual ICollection<tbl_fastRide_canceled> tbl_fastRide_canceled { get; set; }
        public virtual tbl_profile tbl_profile { get; set; }
        public virtual ICollection<tbl_fastRideDetails> tbl_fastRideDetails { get; set; }
        public virtual ICollection<tbl_fastUserRating> tbl_fastUserRating { get; set; }
    }
}
