//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_governmentDetail
    {
        public int govDetail_id { get; set; }
        public int government_id { get; set; }
        public int company_id { get; set; }
    
        public virtual tbl_company tbl_company { get; set; }
        public virtual tbl_government tbl_government { get; set; }
    }
}
