//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_offerRide
    {
        public tbl_offerRide()
        {
            this.tbl_book = new HashSet<tbl_book>();
            this.tbl_complaint = new HashSet<tbl_complaint>();
        }
    
        public int offerRide_ID { get; set; }
        public int user_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public string from_place { get; set; }
        public string to_place { get; set; }
        public string from_place_persian { get; set; }
        public string to_place_persian { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string vehicle_type { get; set; }
        public Nullable<int> no_seats { get; set; }
        public bool middleSeat { get; set; }
        public Nullable<bool> charter { get; set; }
        public string ride_comment { get; set; }
        public string price { get; set; }
        public Nullable<bool> status { get; set; }
        public string statusType { get; set; }
        public Nullable<bool> Cigarette { get; set; }
        public Nullable<bool> Music { get; set; }
        public Nullable<bool> AC { get; set; }
        public Nullable<bool> complaint { get; set; }
        public System.DateTime createdAt { get; set; }
        public string from_latlong { get; set; }
        public string to_latlong { get; set; }
        public Nullable<bool> isAllowFemale { get; set; }
    
        public virtual ICollection<tbl_book> tbl_book { get; set; }
        public virtual ICollection<tbl_complaint> tbl_complaint { get; set; }
        public virtual tbl_profile tbl_profile { get; set; }
        public virtual tbl_vehicle tbl_vehicle { get; set; }
    }
}
