//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vehicle
    {
        public tbl_vehicle()
        {
            this.tbl_fastRideDetails = new HashSet<tbl_fastRideDetails>();
            this.tbl_fastTrack = new HashSet<tbl_fastTrack>();
            this.tbl_offerRide = new HashSet<tbl_offerRide>();
        }
    
        public int vehicle_id { get; set; }
        public int user_id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public string plateNumber { get; set; }
        public string type { get; set; }
        public bool approved { get; set; }
        public string carPhoto { get; set; }
        public string carLicense { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual ICollection<tbl_fastRideDetails> tbl_fastRideDetails { get; set; }
        public virtual ICollection<tbl_fastTrack> tbl_fastTrack { get; set; }
        public virtual ICollection<tbl_offerRide> tbl_offerRide { get; set; }
        public virtual tbl_profile tbl_profile { get; set; }
    }
}
