//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fastRideDetails
    {
        public int ID { get; set; }
        public int fastRide_ID { get; set; }
        public int driver_id { get; set; }
        public int vehicle_id { get; set; }
        public Nullable<System.DateTime> startAt { get; set; }
        public Nullable<System.DateTime> endAt { get; set; }
        public string startLatLong { get; set; }
        public string endLatLong { get; set; }
        public string price { get; set; }
        public string PayBy { get; set; }
    
        public virtual tbl_fastRide tbl_fastRide { get; set; }
        public virtual tbl_profile tbl_profile { get; set; }
        public virtual tbl_vehicle tbl_vehicle { get; set; }
    }
}
