//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_company
    {
        public tbl_company()
        {
            this.tbl_companyDetail = new HashSet<tbl_companyDetail>();
            this.tbl_governmentDetail = new HashSet<tbl_governmentDetail>();
        }
    
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string password { get; set; }
        public string comeFrom { get; set; }
        public string ceoID_path { get; set; }
        public string permissions_path { get; set; }
        public string companyCertificate_path { get; set; }
        public bool isConfirmed { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual ICollection<tbl_companyDetail> tbl_companyDetail { get; set; }
        public virtual ICollection<tbl_governmentDetail> tbl_governmentDetail { get; set; }
    }
}
