//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_accountDetail
    {
        public int AccountDetail_ID { get; set; }
        public int user_id { get; set; }
        public string accountNumber { get; set; }
        public string bankName { get; set; }
        public string shabaNumber { get; set; }
        public string accountHolder { get; set; }
    
        public virtual tbl_profile tbl_profile { get; set; }
    }
}
