//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_general
    {
        public int ID { get; set; }
        public string percentDetect { get; set; }
        public string passengerDetect { get; set; }
        public string fastTrackAmount { get; set; }
        public string perKM { get; set; }
        public string hostAddress { get; set; }
        public string termConditionPath { get; set; }
        public string aboutPath { get; set; }
        public string privacyPolicyPath { get; set; }
    }
}
