//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transDetails
    {
        public int transDetail_ID { get; set; }
        public int transaction_ID { get; set; }
        public int offerRide_ID { get; set; }
        public string userType { get; set; }
        public string amount { get; set; }
        public string KarenroDetect { get; set; }
        public string total { get; set; }
    }
}
