//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userComesFrom
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public bool individual { get; set; }
    
        public virtual tbl_profile tbl_profile { get; set; }
    }
}
