//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile
    {
        public tbl_profile()
        {
            this.tbl_accountDetail = new HashSet<tbl_accountDetail>();
            this.tbl_adminTransaction = new HashSet<tbl_adminTransaction>();
            this.tbl_book = new HashSet<tbl_book>();
            this.tbl_chat = new HashSet<tbl_chat>();
            this.tbl_chatDetails = new HashSet<tbl_chatDetails>();
            this.tbl_companyDetail = new HashSet<tbl_companyDetail>();
            this.tbl_complaint = new HashSet<tbl_complaint>();
            this.tbl_discountDetails = new HashSet<tbl_discountDetails>();
            this.tbl_fastRide = new HashSet<tbl_fastRide>();
            this.tbl_fastRide_canceled = new HashSet<tbl_fastRide_canceled>();
            this.tbl_fastRideDetails = new HashSet<tbl_fastRideDetails>();
            this.tbl_fastTrack = new HashSet<tbl_fastTrack>();
            this.tbl_offerRide = new HashSet<tbl_offerRide>();
            this.tbl_userComesFrom = new HashSet<tbl_userComesFrom>();
            this.tbl_vehicle = new HashSet<tbl_vehicle>();
            this.tbl_WalletTransaction = new HashSet<tbl_WalletTransaction>();
        }
    
        public int user_id { get; set; }
        public string full_name { get; set; }
        public string number { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string birthday { get; set; }
        public string profile_pic { get; set; }
        public string country { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string gender { get; set; }
        public Nullable<bool> approved { get; set; }
        public string deviceToken { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string forgetPasswordToken { get; set; }
        public string cnic_frant { get; set; }
        public string cnic_back { get; set; }
        public string latLong { get; set; }
    
        public virtual ICollection<tbl_accountDetail> tbl_accountDetail { get; set; }
        public virtual ICollection<tbl_adminTransaction> tbl_adminTransaction { get; set; }
        public virtual ICollection<tbl_book> tbl_book { get; set; }
        public virtual ICollection<tbl_chat> tbl_chat { get; set; }
        public virtual ICollection<tbl_chatDetails> tbl_chatDetails { get; set; }
        public virtual ICollection<tbl_companyDetail> tbl_companyDetail { get; set; }
        public virtual ICollection<tbl_complaint> tbl_complaint { get; set; }
        public virtual ICollection<tbl_discountDetails> tbl_discountDetails { get; set; }
        public virtual ICollection<tbl_fastRide> tbl_fastRide { get; set; }
        public virtual ICollection<tbl_fastRide_canceled> tbl_fastRide_canceled { get; set; }
        public virtual ICollection<tbl_fastRideDetails> tbl_fastRideDetails { get; set; }
        public virtual ICollection<tbl_fastTrack> tbl_fastTrack { get; set; }
        public virtual ICollection<tbl_offerRide> tbl_offerRide { get; set; }
        public virtual ICollection<tbl_userComesFrom> tbl_userComesFrom { get; set; }
        public virtual ICollection<tbl_vehicle> tbl_vehicle { get; set; }
        public virtual ICollection<tbl_WalletTransaction> tbl_WalletTransaction { get; set; }
    }
}
