//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chat
    {
        public tbl_chat()
        {
            this.tbl_chatDetails = new HashSet<tbl_chatDetails>();
        }
    
        public int chat_ID { get; set; }
        public int offerRide_ID { get; set; }
        public int user_id { get; set; }
        public string userType { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual tbl_profile tbl_profile { get; set; }
        public virtual ICollection<tbl_chatDetails> tbl_chatDetails { get; set; }
    }
}
