//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_book
    {
        public int book_id { get; set; }
        public int offerRide_ID { get; set; }
        public int user_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string passengerCode { get; set; }
    
        public virtual tbl_offerRide tbl_offerRide { get; set; }
        public virtual tbl_profile tbl_profile { get; set; }
    }
}
