//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cities
    {
        public tbl_cities()
        {
            this.tbl_autoCharges = new HashSet<tbl_autoCharges>();
            this.tbl_autoCharges1 = new HashSet<tbl_autoCharges>();
        }
    
        public int cityID { get; set; }
        public string cityName { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual ICollection<tbl_autoCharges> tbl_autoCharges { get; set; }
        public virtual ICollection<tbl_autoCharges> tbl_autoCharges1 { get; set; }
    }
}
