//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_discountCode
    {
        public tbl_discountCode()
        {
            this.tbl_discountDetails = new HashSet<tbl_discountDetails>();
        }
    
        public int discountID { get; set; }
        public string discountFee { get; set; }
        public string discountCode { get; set; }
        public string availableNumber { get; set; }
        public System.DateTime expireDate { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual ICollection<tbl_discountDetails> tbl_discountDetails { get; set; }
    }
}
