//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_adminBank
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string amount { get; set; }
        public string userType { get; set; }
        public Nullable<int> offerRide_ID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string paymentStatus { get; set; }
        public Nullable<int> transaction_ID { get; set; }
        public Nullable<int> book_id { get; set; }
    }
}
